### ISSUE TITLE
Dependencies on aggregate functions

### ISSUE THREAD

**Issue by johto** [djrobstep/schemainspect#4]
Somewhat similar to #3, I guess, but this fails as well:

```
CREATE AGGREGATE array_accum(anyelement) (
    SFUNC = array_append,
    STYPE = anyarray,
    INITCOND = '{}'
);
CREATE VIEW foov AS SELECT array_accum(1);
```

Stacktrace:

```
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    i = get_inspector(s)
  File "/home/marko/ff/mainenv/lib/python3.4/site-packages/schemainspect/get.py", line 19, in get_inspector
    return ic(c)
  File "/home/marko/ff/mainenv/lib/python3.4/site-packages/schemainspect/pg/__init__.py", line 331, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/home/marko/ff/mainenv/lib/python3.4/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/home/marko/ff/mainenv/lib/python3.4/site-packages/schemainspect/pg/__init__.py", line 340, in load_all
    self.load_deps()
  File "/home/marko/ff/mainenv/lib/python3.4/site-packages/schemainspect/pg/__init__.py", line 357, in load_deps
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"public"."array_accum"(anyelement)'
```

**Comment by djrobstep** [comment]
Good catch. Looks like we need some new code to add the information for these.

**Comment by joninsky** [comment]
Upvote on this.

**Comment by hindolam** [comment]
Looks like the error is still exists. Aggregates are not supported in pg_get_functiondef(oid) and that's throwing an error. Since it blows if aggregates exist and there does not seem quick solution at this stage, does it make sense to exclude aggregates while querying pg_proc table? And maybe note that in documentation

It seems to be at two places
pg/sql/functions.sql
pg/sql/deps.sql
in both places while retrieving names from pg-proc can we simply exclude name that have pg_proc.prokind = 'a' (functions that are aggregates)

**Comment by djrobstep** [comment]
Finally got around to fixing this. Migra still doesn't handle custom aggregates, but at least their presence should no longer cause errors.

**Comment by Astrapolis-peasant** [comment]
Hi, I had the same error with custom type
```
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"btc_type"."vin"
```
