### ISSUE TITLE
Python 3.5.3: "SyntaxError: invalid syntax" due to "f string" usage in command.py

### ISSUE THREAD

**Issue by hi2u** [djrobstep/schemainspect#52]
* I just recently updated schemainspect + migra on a Debian 9 box.  
* Debian 9 comes with: Python 3.5.3
* Looks like the issue is that a newer version of Python is required to use "f strings"

Running the `migra` command alone (no args, or with args), I get a stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 7, in <module>
    from migra import do_command
  File "/usr/local/lib/python3.5/dist-packages/migra/__init__.py", line 4, in <module>
    from .command import do_command
  File "/usr/local/lib/python3.5/dist-packages/migra/command.py", line 9, in <module>
    from .migra import Migration
  File "/usr/local/lib/python3.5/dist-packages/migra/migra.py", line 3, in <module>
    from schemainspect import DBInspector, get_inspector
  File "/usr/local/lib/python3.5/dist-packages/schemainspect/__init__.py", line 4, in <module>
    from .command import do_command
  File "/usr/local/lib/python3.5/dist-packages/schemainspect/command.py", line 34
    thing=f"{dep.kind_dependent_on}: {thing}",
                                            ^
SyntaxError: invalid syntax
```

Link to a couple of relevant lines: https://github.com/djrobstep/schemainspect/blob/master/schemainspect/command.py#L34-L35 (there may be more)

Is backwards compatibility with Python 3.5 an option at all?

**Comment by djrobstep** [comment]
I've removed the f-strings so this should be fixed now :)

I really should have a more well-defined/test list of supported versions (currently the tests only get run with the latest python)
